services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Alerto_apiRest-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__AlertoDb: Host=postgres;Port=5432;Database=alerto_db;Username=postgres;Password=postgres
      ConnectionStrings__Redis: redis:6379,abortConnect=false
    ports:
      - "5070:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: Alerto_apiRest-postgres
    environment:
      POSTGRES_DB: alerto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v15:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alerto_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: Alerto_apiRest-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_v15:
  redis_data:
